trigger:
  branches:
    include:
      - master
      - release/beta/*
      - release/stable/*
      - feature/*

pr: 
  branches:
    include:
      - master
      - release/beta/*
      - release/stable/*

  paths:
    include:
    - '/'
    exclude:
    - .dependabot/
    - .github/
    - .editorconfig
    - '*.md'
    - .all-contributorsrc

resources:
  containers:
  - container: nv-bionic-wasm
    image: unoplatform/wasm-build:3.0

variables:
  windowsHostedVMImage: 'windows-2019'
  windowsScaledPool: 'Windows2019-20200608'
  linuxVMImage: 'ubuntu-latest'
  macOSVMImage: 'macOS-10.15'
  xCodeRoot: '/Applications/Xcode_11.5.app'
  XamarinSDKVersion: 6_10_0

jobs:
- template: build/ci/.azure-devops-windows.yml
  parameters:
    poolName: '$(windowsScaledPool)'

- template: build/ci/.azure-devops-project-template-tests.yml
  parameters:
    vmImage: '$(windowsHostedVMImage)'

- template: build/ci/.azure-devops-uap.yml
  parameters:
    vmImage: '$(windowsHostedVMImage)'

- template: build/ci/.azure-devops-unit-tests.yml
  parameters:
    vmImage: '$(windowsHostedVMImage)'

- template: build/ci/.azure-devops-skia-tests.yml
  parameters:
    vmImage: '$(windowsHostedVMImage)'

- template: build/ci/.azure-devops-docs.yml	
  parameters:	
    vmImage: '$(windowsHostedVMImage)'	

- template: build/ci/.azure-devops-wasm-uitests.yml
  parameters:
    vmImage: '$(linuxVMImage)'

- template: build/ci/.azure-devops-wasm-cs9-preview-validation.yml
  parameters:
    vmImage: '$(linuxVMImage)'

- template: build/ci/.azure-devops-macos.yml
  parameters:
    vmImage: '$(macOSVMImage)'
    xCodeRoot: '$(xCodeRoot)'
    XamarinSDKVersion: '$(XamarinSDKVersion)'

- template: build/ci/.azure-devops-android-tests.yml
  parameters:
    vmImage: '$(macOSVMImage)'
    xCodeRoot: '$(xCodeRoot)'
    XamarinSDKVersion: '$(XamarinSDKVersion)'

- template: build/ci/.azure-devops-ios-tests.yml
  parameters:
    vmImage: '$(macOSVMImage)'
    xCodeRoot: '$(xCodeRoot)'
    XamarinSDKVersion: '$(XamarinSDKVersion)'

- template: build/ci/.azure-devops-screenshot-compare.yml
  parameters:
    vmImage: '$(windowsHostedVMImage)'
